# Generated by Django 5.2 on 2026-09-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='admin_pic',
            field=models.ImageField(default='admin.jpeg', upload_to='admin/'),
        ),
    ]
