# Generated by Django 5.2 on 2026-09-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_admin_admin_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
